service: SlackChannelArchiver
provider:
  name: aws
  timeout: 30 # seconds
  runtime: python3.6
  stage:  ${opt:stage, self:custom.defaultStage}
  region: ${opt:region, self:custom.defaultRegion}
  profile: ${opt:profile, self:custom.defaultProfile}
custom:
  defaultStage: dev
  defaultRegion: ap-northeast-1
  defaultProfile: default
  otherfile:
    environment:
      dev: ${file(./enviroment_dev.yml)}
      prd: ${file(./enviroment_prd.yml)}
  alerts: # alert plugin
    stages:
      - dev
      - prd
    alarms:
      - functionErrors
      - functionThrottles
functions:
  fnc:
    handler: main.handler
    events:
      - schedule: cron(0 3 * * ? *) ## cron(0 3 ? * MON *) # UTC 03:00 ( JST 12:00 ) / Monday
    environment:
      ${self:custom.otherfile.environment.${self:provider.stage}}
plugins:
  - serverless-plugin-aws-alerts
